language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: kOuQeC0//gsiW08LL+AoA2lKd78vIF5QUXp+wrvtRTc/GLxt9z+/kw6SIcE0ZHQP801KwM2oQm72+xJc5yeUkEDOXzgKCEemi3cF97Z6kSg/VwMldqUmQkbeoU5+KlHbZH0ZBmqPGCL1Xz2SemXMEDoJ2tADOGoXwa8Nse6qEnP4/Qfu6Gqq0O72d25s591Y6wf9GabablFI8ersNJBpSCqivWkRxmmCRj9cGpMQK27pyiK8Fxu80nV92BjwEl3AxIivWYERHzJGa3VhQ5vy+m/ZwI16IPRNy1GJU6KryeTS9Z83LCmoAu40M9vHzLlLTUOV3S6xiSB00aT4OrJk1zi+ZXNUvlOnOdLpAVKmF4MfInidPU8Mh+g0RcXi9euQnb9qP1LmB3KxOPqdZ7uT3Zr9CT4OsnQrWdMBFo3omiT1ZeoobO/jaQk4SQMu3jWi5mAMeStQqZ/EKdJ0I0FXg3yUIYARB1dQeQuULeLwhZPpdewzJTP/+xTkJ4WH0oECLXld0SyKHq7HjxiUDPjZEulPgHn60kMI64GBvMXBo6Bij9jlg+5RFw2AeHAjgeKFeNjnPhyhYwHmnQf9bYibaJLz34JlRVX399PD/cyzcRPj8TwETCuiw7/TTwZXoeNkH5MFHIC7InrzKie4YRgPYlIAWQh6ck5/v8OIgKUxu8U=
  app: mighty-ravine-29318
  on:
    repo: abrentgit/goodnest-API
